name: ChirpStack Network Server
version: "1"
url: https://github.com/ezand/chirpstack-addon-repository/tree/main/network-server
slug: chirpstack_network_server
description: OpenSource LoRaWAN® Network Server implementation.
arch: [armhf, armv7, aarch64, amd64, i386]
startup: application
boot: auto
homeassistant_api: true
apparmor: true
init: false
panel_icon: mdi:access-point-network
panel_title: ChirpStack Network Server
ports:
  "8080/tcp": 8080 # API server
