name: ChirpStack Network Server
version: "1"
url: https://github.com/ezand/chirpstack-addon-repository/tree/main/network-server
slug: chirpstack_network_server
description: OpenSource LoRaWAN® Network Server implementation.
arch: [armhf, armv7, aarch64, amd64, i386]
startup: application
boot: auto
homeassistant_api: true
apparmor: true
init: false
panel_icon: mdi:access-point-network
panel_title: ChirpStack Network Server
options:
  logging:
    log_level: "info"
  postgresql:
    dsn: "postgresql://localhost/chirpstack_ns?sslmode=disable"
    max_open_connections: 10
    ca_cert: ""
  redis:
    servers:
      - "localhost:6379"
    cluster: false
    key_prefix: ""
    max_open_connections: 100
    min_idle_connections: 0
  api:
    bind: "0.0.0.0:8080"
  gateway:
    ca_key: ""
    ca_cert: ""
    client_cert_lifetime: "11months 30days 3h 50m 24s"
    allow_unknown_gateways: false
  network:
    net_id: "000000"
    secondary_net_ids: []
    dev_addr_prefixes: []
    enabled_regions: []
    deduplication_delay: "200ms"
    get_downlink_data_delay: "100ms"
    mac_commands_disabled: false
    adr_plugins: []
schema:
  log_level: "match(^TRACE$|^DEBUG$|^INFO$|^WARN$|^ERROR$|^OFF$)"
  json: bool
 postgresql:
    dsn: str?
    max_open_connections: int?
    ca_cert: str?
  redis:
    servers: 
      - str
    cluster: bool
    key_prefix: str?
    max_open_connections: int?
    min_idle_connections: int?
  api:
    bind: str?
  gateway:
    ca_key: str?
    ca_cert: str?
    client_cert_lifetime: str?
    allow_unknown_gateways: bool?
  network:
    net_id: str?
    secondary_net_ids:
      - str
    dev_addr_prefixes:
      - str
    enabled_regions:
      - str
    deduplication_delay: "match(ms$)"
    get_downlink_data_delay: "match(ms$)"
    mac_commands_disabled: bool
    adr_plugins: 
      - str
ports:
  "8080/tcp": 8080 # API server
