name: ChirpStack Server V4
version: "4.7.0.0"
url: https://github.com/Tathar/chirpstack-addon-repository
slug: chirpstack_server
description: OpenSource LoRaWAN® Network Server implementation.
arch: [armhf, armv7, aarch64, amd64, i386]
startup: application
boot: auto
webui: "http://[HOST]:[PORT:8080]/"
# auth_api: true
homeassistant_api: true
# apparmor: true
options:
  mqtt_server: "tcp://127.0.0.1:1883/"
schema:
  mqtt_server: str
ports:
  8080/tcp: 8080
  1700/udp: 1700
ports_description:
  8080/tcp: Web interface
  1700/udp: ChirpStack Gateway port
startup: system
watchdog: tcp://[HOST]:8080
init: false